language: go

sudo: false

go:
  - 1.5.4
  - 1.6.2
  - 1.7.1
  - tip

before_install:
  - go get github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./...
